create_clock -period 20.000 -name CLK -waveform {0.000 10.000} [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports {io_pin[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_pin[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {io_pin[2]}]
set_property PACKAGE_PIN K17 [get_ports CLK]
set_property PACKAGE_PIN U15 [get_ports {io_pin[0]}]
set_property PACKAGE_PIN W15 [get_ports {io_pin[1]}]
set_property PACKAGE_PIN U17 [get_ports {io_pin[2]}]
