create_clock -period 20.000 -name CLK -waveform {0.000 10.000} [get_ports CLK]

set_property PACKAGE_PIN R18 [get_ports LED1]
set_property PACKAGE_PIN W16 [get_ports LED2]
set_property PACKAGE_PIN T16 [get_ports LED3]
set_property PACKAGE_PIN R16 [get_ports LED4]
set_property PACKAGE_PIN K17 [get_ports CLK]

set_property PACKAGE_PIN U14 [get_ports {LED[0]}]
set_property PACKAGE_PIN U19 [get_ports {LED[1]}]
set_property PACKAGE_PIN W18 [get_ports {LED[2]}]
set_property PACKAGE_PIN V18 [get_ports {LED[3]}]
set_property PACKAGE_PIN N17 [get_ports {LED[4]}]
set_property PACKAGE_PIN W19 [get_ports {LED[5]}]
set_property PACKAGE_PIN Y19 [get_ports {LED[6]}]
set_property PACKAGE_PIN Y18 [get_ports {LED[7]}]

set_property PACKAGE_PIN N20 [get_ports LK_CLK]
set_property PACKAGE_PIN N18 [get_ports LK_STB]
set_property PACKAGE_PIN P18 [get_ports LK_DIO]
set_property PACKAGE_PIN P19 [get_ports PROBE]
set_property PACKAGE_PIN U18 [get_ports IR]
set_property PACKAGE_PIN T20 [get_ports RX]

set_property PACKAGE_PIN D19 [get_ports {hdmi_p[0]}]
set_property PACKAGE_PIN D20 [get_ports {hdmi_n[0]}]
set_property PACKAGE_PIN C20 [get_ports {hdmi_p[1]}]
set_property PACKAGE_PIN B20 [get_ports {hdmi_n[1]}]
set_property PACKAGE_PIN B19 [get_ports {hdmi_p[2]}]
set_property PACKAGE_PIN A20 [get_ports {hdmi_n[2]}]
set_property PACKAGE_PIN H16 [get_ports {hdmi_p[3]}]
set_property PACKAGE_PIN H17 [get_ports {hdmi_n[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports LED1]
set_property IOSTANDARD LVCMOS33 [get_ports LED2]
set_property IOSTANDARD LVCMOS33 [get_ports LED3]
set_property IOSTANDARD LVCMOS33 [get_ports LED4]

set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports LK_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports LK_STB]
set_property IOSTANDARD LVCMOS33 [get_ports LK_DIO]
set_property IOSTANDARD LVCMOS33 [get_ports PROBE]
set_property IOSTANDARD LVCMOS33 [get_ports IR]
set_property IOSTANDARD LVCMOS33 [get_ports RX]

set_property IOSTANDARD TMDS_33 [get_ports {hdmi_p[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_n[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_p[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_n[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_p[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_n[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_p[3]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_n[3]}]
